spring:
  application:
    name: eclipse-hotel-reservations

  # Configurações de Conexão do Banco de Dados
  datasource:
    url: jdbc:postgresql://${DB_SERVER_URL:host.docker.internal}:${DB_SERVER_PORT:5432}/${DB_SCHEMA:dbdev}?sslmode=disable
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000


  # Configurações do Hibernate / JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


  cache:
    type: simple

# Configuração da Porta
server:
  port: 8080

# Assinatura do Token
api:
  security:
    token:
      issuer: eclipse-hotel

# Url base do Brasil Api
brasilapi:
  cep:
    base-url: https://brasilapi.com.br/api/cep/v1

# Spring Cloud Feign
feign:
  client:
    config:
      default:
        connect-timeout: 2000
        read-timeout: 3000

